## Problem

$$f(w_1, w_2) = 0.1w_1^2 + 2w_2^2 \;\;\;\;\;\;\;(1)$$

In [1]:
import numpy as np

### RMSprop

In [2]:
def df_w(W):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """
    #################### YOUR CODE HERE ####################

    dW = np.array([0.2 * W[0], 4 * W[1]])

    ########################################################
    return dW

In [3]:
def RMSProp(W, dW, lr, S, gamma):
    """
    Thực hiện thuật tóan RMSProp để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients
    gamma -- float: hệ số long-range average
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients sau khi đã cập nhật
    """
    epsilon = 1e-6
    #################### YOUR CODE HERE ####################

    S = gamma * S + (1 - gamma) * (dW ** 2)
    W = W - lr * dW / np.sqrt(S + epsilon)

    ########################################################
    return W, S

In [5]:
def train_p1(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # initial
    W = np.array([-5, -2], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)
    results = [W]
    #################### YOUR CODE HERE ####################
    # Tạo vòng lặp theo số lần epochs
    # tìm gradient dW gồm dw1 và dw2
    # dùng thuật toán optimization cập nhật w1, w2, s1, s2
    # append cặp [w1, w2] vào list results

    for epoch in range(epochs):
        dW = df_w(W)
        W, S = RMSProp(W, dW, lr, S, 0.999)
        results.append(W)

    ########################################################
    return results

In [6]:
train_p1(RMSProp, lr=0.3, epochs=30)

[array([-5., -2.], dtype=float32),
 array([4.48209312, 7.48675887]),
 array([-1.85027369, -1.67897405]),
 array([0.67106645, 0.33087226]),
 array([-0.23961786, -0.0650573 ]),
 array([0.08553189, 0.01282813]),
 array([-0.03058006, -0.00253714]),
 array([0.0109536 , 0.00050331]),
 array([-0.00393094, -0.00010015]),
 array([1.41337233e-03, 1.99875314e-05]),
 array([-5.09140491e-04, -4.00107571e-06]),
 array([1.83754529e-04, 8.03332468e-07]),
 array([-6.64441424e-05, -1.61775062e-07]),
 array([2.40709067e-05, 3.26755053e-08]),
 array([-8.73663461e-06, -6.61948696e-09]),
 array([3.17695268e-06, 1.34497573e-09]),
 array([-1.15742018e-06, -2.74087665e-10]),
 array([4.22458418e-07, 5.60204140e-11]),
 array([-1.54485736e-07, -1.14836985e-11]),
 array([5.65982754e-08, 2.36098257e-12]),
 array([-2.07743429e-08, -4.86828737e-13]),
 array([7.63940573e-09, 1.00676702e-13]),
 array([-2.81448503e-09, -2.08808431e-14]),
 array([1.03882956e-09, 4.34340482e-15]),
 array([-3.84144445e-10, -9.06093015e-16]